# Generated by Django 6.0.6 on 2026-06-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=100)),
                ('simu', models.CharField(max_length=15)),
                ('idadi_ya_watu', models.IntegerField()),
                ('tarehe_na_muda', models.DateTimeField()),
                ('ujumbe', models.TextField(blank=True, null=True)),
                ('tarehe_ya_kuomba', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='is_available',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vyakula/'),
        ),
    ]
