# Generated by Django 6.0.6 on 2026-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservation_remove_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
