# Generated by Django 6.0.6 on 2026-07-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservation_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=100)),
                ('simu', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('items_json', models.JSONField(help_text='Vitu vilivyoagizwa')),
                ('jumla', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('confirmed', 'Imethibitishwa'), ('completed', 'Imekamilika'), ('cancelled', 'Imeghairiwa')], default='pending', max_length=20)),
                ('tarehe_ya_kuagiza', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
